FROM python:3.9
EXPOSE 5000
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get install -y sqlite3
RUN pip install flask
RUN pip install pyjwt
RUN pip install flask_cors
CMD ["flask", "--app", "games", "run", "--host=0.0.0.0"]