openapi: 3.1.0
info:
  title: CTF401 - API CHALLENGES
  description: |-
    API Challenges documentation for the project "CTF401". 

    Some useful links:
    - [Discord](https://discord.gg/pvkHnzk7)
    - [Trello](https://trello.com/b/K8nrKpmh)
    - [GitHub](https://github.com/perrze/ctf401)

  termsOfService: http://swagger.io/terms/
  contact:
    email: sarah.dambielle@etudiant.univ-rennes1.fr
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:5000
tags:
  - name: challenges
    description: CTF Challenges information
paths:
  /challenges:
    get:
      tags:
        - challenges
      summary: Return all CTF challenges
      description: Return all CTF challenges
      operationId: getChallenges
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenges'
    post:
      tags:
        - challenges
      summary: Create a new CTF challenge
      description: Create a new CTF challenge
      operationId: createChallenge
      requestBody:
        description: Create CTF challenge
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Challenge'
          application/xml:
            schema:
              $ref: '#/components/schemas/Challenge'
      responses: 
        '200':
            description: Challenge created
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Challenge'
        '405':
            description: Invalid ID
  /challenges/{id}:
    get:
      tags:
        - challenges
      summary: Return CTF challenge by ID
      description: Retourne CTF challenge by ID
      operationId: getChallengeByID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: 'a9b48bb7-9e16-4017-a04b-2f5afbfd2bc3'
          description: Challenge ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenges'
    patch:
      tags:
        - challenges
      summary: Modify CTF challenge's information by ID
      description: Modify CTF challenge's information by ID
      operationId: modifyChallengeByID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: 'a9b48bb7-9e16-4017-a04b-2f5afbfd2bc3'
          description: Challenge ID
      requestBody:
        description: Modify CTF challenge's information by ID
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Challenge'
          application/xml:
            schema:
              $ref: '#/components/schemas/Challenge'
      responses: 
        '200':
            description: Challenge modified
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Challenge'
        '404':
            description: ID not found
        '405':
            description: Invalid input
    delete:
      tags:
        - challenges
      summary: Delete CTF challenge's information by ID
      description: Delete CTF challenge's information by ID
      operationId: deleteChallengeByID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: 'a9b48bb7-9e16-4017-a04b-2f5afbfd2bc3'
          description: Challenge ID
      responses:
        '200': 
          description: Challenge deleted
        '404':
          description: ID Not Found
  /challenges/{id}/check_flag:
    get:
      tags:
        - challenges
      summary: Check CTF challenge response 
      description: Check CTF challenge response 
      operationId: checkChallengeReponse
      parameters:
        - in: query
          name: flag
          required: true
          schema:
            type: string
            example: 'IUTSM'
          description: Flag found
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /challenges/{id}/status:
    get:
      tags:
        - challenges
      summary: Check CTF challenge status 
      description: Check CTF challenge status 
      operationId: checkChallengeStatus
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: 'a9b48bb7-9e16-4017-a04b-2f5afbfd2bc3'
          description: Challenge ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /challenges/{id_game}:
    get:
      tags:
        - challenges
      summary: Return all CTF challenges for one game
      description: Return all CTF challenges for one game
      operationId: getChallengesByGame
      parameters:
        - in: path
          name: id_game
          required: true
          schema:
            type: string
            format: uuid
            example: 'a682b3d6-50cd-4f26-91fd-2eb66c249303'
          description: Challenge status
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenges'
  /challenges/{id_game}/{status}:
    get:
      tags:
        - challenges
      summary: Return CTF challenges by status for one game
      description: Return CTF challenges by status for one game
      operationId: getChallengesByStatus
      parameters:
        - in: path
          name: id_game
          required: true
          schema:
            type: string
            format: uuid
            example: 'a682b3d6-50cd-4f26-91fd-2eb66c249303'
          description: Game ID
        - in: path
          name: status
          required: true
          schema:
            type: string
            enum:
              - active
              - inactive
            example: 'active'
          description: Challenge status
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenges'
  /challenges/{id_game}/{tag}:
    get:
      tags:
        - challenges
      summary: Return CTF challenges game by tag
      description: Return CTF challenges game by tag
      operationId: getChallengesByGameAndTag
      parameters:
        - in: path
          name: id_game
          required: true
          schema:
            type: string
            format: uuid
            example: 'a682b3d6-50cd-4f26-91fd-2eb66c249303'
          description: Game ID
        - in: path
          name: tag
          required: true
          schema:
            type: string
            example: 'easy'
          description: Challenge tag
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenges'
components:
  schemas:
    Status: 
      type: object
      properties:
        isActive:
          type: boolean
          example: False
    Response: 
      type: object
      properties:
        response: 
          type: string
          example: 'IUTSM'
        check:
          type: boolean
          example: True
    Challenge:
      type: object
      properties:
        id_challenge:
          type: string
          format: uuid
          example: 'a682b3d6-50cd-4f26-91fd-2eb66c249301'
          description: 'Challenge ID'
        id_game:
          type: string
          format: uuid
          example: 'a682b3d6-50cd-4f26-91fd-2eb66c249303'
          description: 'Game ID'
        tags:
          type: string
          example: 'easy, Réseaux, Sécurité'
          description: 'Challenge tags'
        nb_points:
          type: integer
          example: 300
          description: 'Number of points won after solving the challenge'
        creator:
          type: string
          example: 'clasheureux'
          description: 'Challenge creator'
        name:
          type: string
          example: 'Analyser des paquets'
          description: 'Challenge name'
        description:
          type: string
          example: 'Analyser des paquets pour trouver le flag !'
          description: 'Challenge description'
        flag:
          type: string
          example: 'IUTSM'
          description: 'Challenge solution'
        status:
          type: boolean
          example: True
          descritpion: 'Activate or desactivate the challenge'
        files:
          type: string
          example: '/user/file.txt, /user/file2.py, /user/img1.png'
          description: 'Challenge files'
      xml:
        name: challenge
    Challenges:
      type: array
      items: 
        $ref: "#/components/schemas/Challenge"
      xml: challenges